mod-name: NearFutureAeronautics
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - NearFutureAeronautics
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.2.3
    location: s3
  B9PartSwitch:
    version: 2.20.0
    location: s3
  CommunityResourcePack:
    version: 1.4.2
    location: s3
  WildBlueIndustries:
    version: 1.9.0
    location: s3
  DeployableEngines:
    tag: 1.3.1
    location: github
    repository: post-kerbin-mining-corporation/DeployableEngines
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 1957  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 301919  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
